imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DichVuNhaCuaBusinessBundle/Resources/config/services.yml" }
    - { resource: "@DichVuNhaCuaProjectBundle/Resources/config/services.yml" }
    - { resource: "@DichVuNhaCuaApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
          datetime_functions:
            DATE: DoctrineExtensions\Query\Mysql\Date
            MONTH: DoctrineExtensions\Query\Mysql\Month
            YEAR: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    #spool:
        #type: "file"
        #path: '%kernel.root_dir%/logs/spool'

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
    from_email:
        address: "ttson284@gmail.com"
        sender_name: "Dich Vu Nha Cua Support"
    registration:
        form:
            type: AppBundle\Form\Type\RegistrationType
        confirmation:
            enabled: true
            template: '@App/emails/User/confirm_email.html.twig'
    service:
        mailer: fos_user.mailer.twig_swift
fos_oauth_server:
    db_driver:           orm
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username
# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false
nelmio_api_doc: ~
# FOSRest Configuration
fos_rest:
    versioning:
      enabled: true
      resolvers:
          query: true
          custom_header: true
          media_type:
              enabled: true
              regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    routing_loader:
      default_format: json
      include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@App/default/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
vich_uploader:
    db_driver: orm
    mappings:
        business_images:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:         '/uploads/business_images'
            upload_destination: '%kernel.root_dir%/../web/uploads/business_images'
            namer: vich_uploader.namer_uniqid
        business_logo:
            uri_prefix:         '/uploads/business_logo'
            upload_destination: '%kernel.root_dir%/../web/uploads/business_logo'
oneup_uploader:
    mappings:
        business_images:
            frontend: blueimp
        business_logo:
            frontend: blueimp
easy_admin:
    site_name: '<img src="/bundles/app/images/logo.png" />'
    design:
        menu:
            - { label: 'Inventory' }
            - { entity: 'Project', label: 'Lead', icon: 'briefcase' }
            - { entity: 'Business', label: 'Pros', icon: 'briefcase' }
            - { entity: 'BusinessImages', label: 'Images', icon: 'picture-o' }
            - { label: 'User Management' }
            - { entity: 'User', label: 'Website User', icon: 'user' }
            - { label: 'System Management' }
            - { entity: 'Categories', label: 'Category', icon: 'list' }
            - { entity: 'Location', label: 'Location', icon: 'map-marker' }
            - { entity: 'LocationType', label: 'Location Type', icon: 'map-marker' }
            - { entity: 'ProjectPeriod', label: 'Project Period', icon: 'calendar' }
            - { entity: 'ProjectStatus', label: 'Project Plan', icon: 'calendar' }
        color_scheme: 'dark'
        assets:
            favicon: 'favicon.ico'
    entities:
        BusinessImages:
          class: DichVuNhaCua\BusinessBundle\Entity\BusinessImages
          list:
            fields:
                - { property: 'file_name', type: 'image', base_path: '/uploads/business_images' }
                - { property: 'business', type: 'association'}
                - 'updated_at'
        Location:
          class: AppBundle\Entity\Location
        LocationType:
          class: AppBundle\Entity\LocationType
        ProjectPeriod:
          class: DichVuNhaCua\ProjectBundle\Entity\ProjectPeriod
        ProjectStatus:
           class: DichVuNhaCua\ProjectBundle\Entity\ProjectStatus
        Business:
            class: DichVuNhaCua\BusinessBundle\Entity\Business
            label: 'Pros'
            list:
                title: '%%entity_label%% Management'
                fields:
                    - 'id'
                    - 'name'
                    - 'address'
                    - 'phone'
                    - 'email'
                    - { property: 'created_at', type: 'datetime' }
                    - { property: 'logo', type: 'image', base_path: '/uploads/business_logo' }
            form:
                title: '%%entity_label%% Management'
                fields:
                    - 'name'
                    - 'address'
                    - 'phone'
                    - 'fax'
                    - 'email'
                    - 'website'
                    - 'employees'
                    - { property: 'about', type: 'ckeditor' }
                    - { property: 'categories', type: 'entity',
                        type_options: {
                          class: 'DichVuNhaCua\BusinessBundle\Entity\Categories',
                          expanded: true,
                          multiple: true,
                          choice_label: 'name',
                        }
                      }
                    - { property: 'imageFile', type: 'vich_image', label: 'Company Logo' }
                    - { property: 'images', type: 'collection',
                          type_options: {
                            entry_type: 'DichVuNhaCua\BusinessBundle\Form\BusinessImagesType',
                            mapped: 'business',
                            by_reference: false
                          }
                      }
                    - { property: 'featured', type: 'checkbox', label: 'Featured?' }
                    - { property: 'status', type: 'checkbox', label: 'Is Active?' }
                    - { property: 'verified', type: 'checkbox', label: 'Approved?' }
                    - { property: 'created_at', type: 'datetime',type_options: {disabled: true}}
                    - { property: 'updated_at', type: 'datetime',type_options: {disabled: true}}
        Categories:
            class: DichVuNhaCua\BusinessBundle\Entity\Categories
        User:
            class: AppBundle\Entity\User
            label: 'Website User Management'
            new:
                fields:
                    - 'firstName'
                    - 'lastName'
                    - 'email'
                    - 'username'
                    - 'enabled'
                    - { property: 'plainPassword', type: 'text', type_options: { required: true } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_BU_OWNER': 'ROLE_BU_OWNER', 'ROLE_CUSTOMER_SUPPORT': 'ROLE_CUSTOMER_SUPPORT', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }
                form_options: { validation_groups: ['Registration'] }
            edit:
                fields:
                    - 'firstName'
                    - 'lastName'
                    - 'email'
                    - 'username'
                    - 'enabled'
                    - 'lastLogin'
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_BU_OWNER': 'ROLE_BU_OWNER', 'ROLE_CUSTOMER_SUPPORT': 'ROLE_CUSTOMER_SUPPORT', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }
                form_options: { validation_groups: ['Profile'] }
        Project:
            class: DichVuNhaCua\ProjectBundle\Entity\Project
            label: 'Lead'
            list:
                actions:
                    - { name: 'admin_business_matching', type: 'route', label: 'Matching Pros', icon: 'suitcase' }
                    - { name: 'edit', icon: 'edit' }
                    - 'search'
                    - '-delete'
                title: '%%entity_label%% Management'
                fields:
                    - id
                    - { property: 'category', type: 'association' , label: 'Industry',
                         type_options: {
                           class: 'DichVuNhaCua\BusinessBundle\Entity\Categories',
                           choice_label: 'name',
                         }
                      }
                    - { property: 'projectStatus', type: 'association' , label: 'Project Status',
                         type_options: {
                           class: 'DichVuNhaCua\ProjectBundle\Entity\ProjectStatus',
                           choice_label: 'name',
                         }
                      }
                    - { property: 'city', type: 'association' , label: 'Location',
                         type_options: {
                           class: 'AppBundle\Entity\Location',
                           choice_label: 'name',
                         }
                      }
                    - 'phone'
                    - 'email'
                    - { property: 'created_at', type: 'datetime' }
            form:
                title: '%%entity_label%% Management'
                fields:
                    - { property: 'createdBy', type: 'entity',
                        type_options: {
                          class: 'AppBundle\Entity\User',
                          choice_label: 'userName',
                        }
                      }
                    - 'name'
                    - { property: 'category', type: 'entity',
                        type_options: {
                          class: 'DichVuNhaCua\BusinessBundle\Entity\Categories',
                          choice_label: 'name',
                        }
                      }

                    - { property: 'projectStatus', type: 'entity',
                        type_options: {
                          class: 'DichVuNhaCua\ProjectBundle\Entity\ProjectStatus',
                          choice_label: 'name',
                        }
                      }
                    - { property: 'projectPeriod', type: 'entity',
                        type_options: {
                          class: 'DichVuNhaCua\ProjectBundle\Entity\ProjectPeriod',
                          choice_label: 'name',
                        }
                      }
                    - { property: 'projectLocationType', type: 'entity',
                        type_options: {
                          class: 'AppBundle\Entity\LocationType',
                          choice_label: 'name',
                        }
                      }
                    - 'address'
                    - { property: 'city', type: 'entity',
                        type_options: {
                          class: 'AppBundle\Entity\Location',
                          choice_label: 'name',
                        }
                      }
                    - 'firstName'
                    - 'lastName'
                    - 'email'
                    - 'phone'
                    - { property: 'detail', type: 'ckeditor' }
                    - { property: 'created_at', type: 'datetime',type_options: {disabled: true}}
                    - { property: 'updated_at', type: 'datetime',type_options: {disabled: true}}