# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_BU_OWNER:      ROLE_USER
        ROLE_CUSTOMER_SUPPORT: ROLE_ADMIN
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        ROLE_ADMIN:         [ROLE_BU_OWNER, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api:
            pattern:    ^/api/v1
            fos_oauth:  true
            stateless:  true
            anonymous:  true # note that anonymous access is now enabled
        main:
            pattern: ^/
            anonymous: true
            logout: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret%'
    access_control:
        - { path: ^/home-service-provider, role: ROLE_BU_OWNER }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/api/v1/register, role: IS_AUTHENTICATED_ANONYMOUSLY }