<?php

namespace AppBundle\Entity\Repository;

use Doctrine\DBAL\Types\Type;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $name
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLocationByName($name)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.name LIKE :cityName')
            ->setParameter('cityName', '%'.$name.'%', Type::STRING);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
