<?php

namespace AppBundle\Entity\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends EntityRepository
{
    /**
     * @param array $userIds
     * @param int   $groupId
     * @return array
     */
    public function getUserIdsByGroupId(array $userIds, int $groupId)
    {
        $results = array();

        /** @var QueryBuilder $queryBuilder */
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $userIdsStr = empty($userIds) ? 0 : implode(',', $userIds);

        $userCustomerList = $queryBuilder->from('ICareUserBundle:UserGroup', 'userGroup')
            ->select('userGroup.userId')
            ->where('userGroup.groupId = :groupId')
            ->andWhere("userGroup.userId IN (".$userIdsStr.")")
            ->setParameter('groupId', $groupId, Type::INTEGER)
            ->getQuery()
            ->getScalarResult();

        if (!empty($userCustomerList)) {
            foreach ($userCustomerList as $userCustomer) {
                $results[] = $userCustomer['userId'];
            }
        }

        return $results;
    }
}
