<?php

namespace DichVuNhaCua\ProjectBundle\Entity\Repository;

use Doctrine\DBAL\Types\Type;

/**
 * ProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposalRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $projecId
     *
     * @return \Doctrine\ORM\Query
     */
    public function getProposalByProjectId(int $projecId)
    {
        $queryBuilder = $this->getEntityManager()
            ->createQueryBuilder()->from('DichVuNhaCuaProjectBundle:Proposal', 'p');

        $queryBuilder->where('p.project = :projectId');
        $queryBuilder->setParameter('projectId', $projecId, Type::INTEGER);

        return $queryBuilder->select('p')->getQuery()->getResult();
    }
}
